[tool.pylama]
format = "pylint"
linters = "pycodestyle, pyflakes, isort"

[tool.pylama.linter.pycodestyle]
max_line_length = 119

[tool.autopep8]
max_line_length = 119
in-place = true
recursive = true
aggressive = 3

[tool.isort]
line_length = 119
multi_line_output = 1

[tool.black]
line-length = 119